from os import system
import sys
from time import sleep
device = sys.argv[1]
print(device)

system(f"parted -a optimal {device} --script print")
print("* Creating GPT Label")
system(f"parted -a optimal {device} --script mklabel gpt")
print("* Creating bios boot partition")
system(f"parted -a optimal {device} --script mkpart primary 1mib 3mib")
system(f"parted -a optimal {device} --script name 1 grub")
system(f"parted -a optimal {device} --script set 1 bios_grub on")
print("* Creating EFI Partition")
system(f"parted -a optimal {device} --script mkpart primary 3mib 131mib")
system(f"parted -a optimal {device} --script name 2 boot")
print("* Making swap partition")
system(f"parted -a optimal {device} --script mkpart primary 131mib 643mib")
system(f"parted -a optimal {device} --script name 3 swap")
print("* Making rootfs")
system(f"parted -a optimal {device} --script mkpart primary 643mib -1")
system(f"parted -a optimal {device} --script name 4 rootfs")
print("* Setting EFI Partition as EFI partition...")
system(f"parted -a optimal {device} --script set 2 boot on")
system(f"parted -a optimal {device} --script print")
print("* Formatting new partitions")
system(f"mkfs.vfat {device}1")
system(f"mkfs.vfat {device}2")
system(f"mkfs.ext4 {device}4")
system(f"mkswap {device}3")
print("* Activating swap")
system(f"swapon {device}3")
system(f"mount {device}4 /mnt/gentoo")

print("Partitioning success!")